TUNE=base
EXT=ql_riscv_llvm17-rv64gcb
NUMBER=464
NAME=h264ref
SOURCES= annexb.c biariencode.c block.c cabac.c configfile.c context_ini.c \
	 decoder.c explicit_gop.c fast_me.c filehandle.c fmo.c header.c image.c \
	 intrarefresh.c leaky_bucket.c lencod.c loopFilter.c macroblock.c \
	 mb_access.c mbuffer.c memalloc.c mv-search.c nal.c nalu.c nalucommon.c \
	 output.c parset.c parsetcommon.c q_matrix.c q_offsets.c ratectl.c \
	 rdopt.c rdopt_coding_state.c rdpicdecision.c refbuf.c rtp.c sei.c \
	 slice.c transform8x8.c vlc.c weighted_prediction.c specrand.c
EXEBASE=h264ref
NEED_MATH=1
BENCHLANG=C
ONESTEP=
CONESTEP=

CC               = /home/xzp/lib/llvm-riscv-17.0.0-rc2/bin/clang --target=riscv64-unknown-linux-gnu --gcc-toolchain=/home/xzp/lib/gnu-riscv64 --sysroot=/home/xzp/lib/gnu-riscv64/sysroot/
COPTIMIZE        = -std=c89 -Wno-int-conversion -O3 -ffast-math -march=rv64gc_zba_zbb_zbc_zbs -flto -ffp-contract=off  -Wno-compound-token-split-by-macro  -static -w
CPORTABILITY     = -fsigned-char                                      
CXX              = /home/xzp/lib/llvm-riscv-17.0.0-rc2/bin/clang++ --target=riscv64-unknown-linux-gnu --gcc-toolchain=/home/xzp/lib/gnu-riscv64 --sysroot=/home/xzp/lib/gnu-riscv64/sysroot/
CXXOPTIMIZE      = -std=c++98 -O3 -ffast-math -march=rv64gc_zba_zbb_zbc_zbs -flto -ffp-contract=off -Wno-compound-token-split-by-macro -static
EXTRA_LDFLAGS    = -z muldefs -fuse-ld=lld
EXTRA_LIBS       = -lm
FPBASE           = yes
OS               = unix
PORTABILITY      = -DSPEC_CPU_LP64
abstol           = 
action           = setup
allow_extension_override = 0
backup_config    = 1
baseexe          = h264ref
basepeak         = 0
benchdir         = benchspec
benchmark        = 464.h264ref
bindir           = exe
calctol          = 0
changedmd5       = 0
check_integrity  = 1
check_md5        = 1
check_version    = 1
command_add_redirect = 0
commanderrfile   = speccmds.err
commandexe       = h264ref_base.ql_riscv_llvm17-rv64gcb
commandfile      = speccmds.cmd
commandoutfile   = speccmds.out
commandstdoutfile = speccmds.stdout
compareerrfile   = compare.err
comparefile      = compare.cmd
compareoutfile   = compare.out
comparestdoutfile = compare.stdout
compile_error    = 0
compwhite        = 1
configdir        = config
configpath       = /home/xzp/speccpu2006-v1.0.1/config/riscv_llvm17-rv64gcb_jmalloc.cfg
copies           = 1
datadir          = data
delay            = 0
deletebinaries   = 0
deletework       = 0
difflines        = 10
dirprot          = 511
endian           = 12345678
env_vars         = 0
exitvals         = spec_exit
expand_notes     = 0
expid            = 
ext              = ql_riscv_llvm17-rv64gcb
fake             = 0
feedback         = 1
flag_url_base    = http://www.spec.org/auto/cpu2006/flags/
floatcompare     = 1
help             = 0
http_proxy       = 
http_timeout     = 30
hw_avail         = 
hw_cpu_mhz       = 2100
hw_cpu_name      = S2500
hw_disk          = None
hw_memory        = 
hw_model         = S2500
hw_nchips        = 
hw_ncores        = 
hw_ncoresperchip = 
hw_ncpuorder     = 
hw_nthreadspercore = 
hw_ocache        = None
hw_other         = None
hw_pcache        = None
hw_scache        = None
hw_tcache        = None
hw_vendor        = 
ignore_errors    = 0
ignore_sigint    = 0
ignorecase       = 
info_wrap_columns = 50
inputdir         = input
iteration        = -1
iterations       = 3
license_num      = 2656
line_width       = 0
locking          = 1
log              = CPU2006
log_line_width   = 0
logname          = /home/xzp/speccpu2006-v1.0.1/result/CPU2006.179.log
lognum           = 179
mach             = default
mail_reports     = all
mailcompress     = 0
mailmethod       = smtp
mailport         = 25
mailserver       = 127.0.0.1
mailto           = 
make             = specmake
make_no_clobber  = 0
makeflags        = -j16
max_active_compares = 0
mean_anyway      = 1
min_report_runs  = 3
minimize_builddirs = 0
minimize_rundirs = 0
name             = h264ref
nc               = 0
need_math        = 1
no_input_handler = close
no_monitor       = 
notes_wrap_columns = 0
notes_wrap_indent =     
num              = 464
obiwan           = 
os_exe_ext       = 
output           = asc
output_format    = asc,csv,html,text,pdf
output_root      = 
outputdir        = output
path             = /home/xzp/speccpu2006-v1.0.1/benchspec/CPU2006/464.h264ref
plain_train      = 1
prefix           = 
rate             = 0
rawfile          = 
rawformat        = 0
realuser         = your name here
rebuild          = 0
reftime          = reftime
reltol           = 
reportable       = 0
resultdir        = result
review           = 0
run              = all
runspec          = /home/xzp/speccpu2006-v1.0.1/bin/runspec -c riscv_llvm17-rv64gcb_jmalloc.cfg --size=ref --noreportable --tune=base --iterations=3 --speed --action=setup 464
safe_eval        = 1
section_specifier_fatal = 1
sendmail         = /usr/sbin/sendmail
setpgrp_enabled  = 1
setprocgroup     = 1
shrate           = 0
sigint           = 2
size             = ref
skipabstol       = 
skipobiwan       = 
skipreltol       = 
skiptol          = 
smarttune        = base
specdiff         = specdiff
specmake         = Makefile.YYYtArGeTYYYspec
specrun          = specinvoke
speed            = 1
srcalt           = 
srcdir           = src
stagger          = 10
strict_rundir_verify = 1
subworkdir       = work
sw_avail         = 
sw_base_ptrsize  = 64-bit
sw_file          = None
sw_os            = 
sw_other         = None
sw_peak_ptrsize  = 64-bit
sw_state         = Multi-user
sysinfo_program  = 
table            = 1
teeout           = 1
tester_name      = Phytium
top              = /home/xzp/speccpu2006-v1.0.1
tune             = base
uid              = 1003
unbuffer         = 1
update-flags     = 0
use_submit_for_speed = 0
username         = xzp
vendor           = anon
vendor_makefiles = 0
verbose          = 5
version          = 0
version_url      = http://www.spec.org/auto/cpu2006/current_version
workdir          = run
worklist         = list
