# Include standard template for this suite
-include $(SPEC)/benchspec/Makefile-S.defaults

nomakefiles:
	@echo "*** Whoops!  I didn't find a Makefile.defaults file."
	@echo "*** Your distribution is probably corrupt."
	@echo
